--
-- Drop tables
--

DROP TABLE UTE_ACCESSI              CASCADE CONSTRAINTS PURGE;
DROP TABLE UTE_UTENTI_ANAGRAFICHE   CASCADE CONSTRAINTS PURGE;
DROP TABLE UTE_UTENTI               CASCADE CONSTRAINTS PURGE;
DROP TABLE UTE_RUOLI_RISORSE        CASCADE CONSTRAINTS PURGE;
DROP TABLE UTE_RUOLI                CASCADE CONSTRAINTS PURGE;

