--
-- Drop tables
--

DROP TABLE UTE_ACCESSI              CASCADE CONSTRAINTS PURGE;
DROP TABLE UTE_UTENTI               CASCADE CONSTRAINTS PURGE;
DROP TABLE UTE_RUOLI_RISORSE        CASCADE CONSTRAINTS PURGE;
DROP TABLE UTE_RUOLI                CASCADE CONSTRAINTS PURGE;

DROP TABLE ANA_COMUNI               CASCADE CONSTRAINTS PURGE;
DROP TABLE ANA_REGIONI              CASCADE CONSTRAINTS PURGE;
