--
-- Tables
--

-- Applicazione

CREATE TABLE ANA_REGIONI (
  ID_REGIONE          VARCHAR2(3)     NOT NULL,
  DESCRIZIONE         VARCHAR2(50),
  CONSTRAINT PK_ANA_REGIONI PRIMARY KEY (ID_REGIONE));

CREATE TABLE ANA_COMUNI (
  ID_COMUNE           VARCHAR2(6)     NOT NULL,
  FISCALE             VARCHAR2(4),
  PROVINCIA           VARCHAR2(3),
  DESCRIZIONE         VARCHAR2(50),
  ID_REGIONE          VARCHAR2(3)     NOT NULL,
  CONSTRAINT PK_ANA_COMUNI PRIMARY KEY (ID_COMUNE),
  CONSTRAINT FK_ANA_COM_REG FOREIGN KEY (ID_REGIONE) REFERENCES ANA_REGIONI(ID_REGIONE));

-- Utenti
  
CREATE TABLE UTE_RUOLI (
  ID_RUOLO            VARCHAR2(50)    NOT NULL,
  DESCRIZIONE         VARCHAR2(100)   NOT NULL,
  ATTIVO              NUMBER(1)       NOT NULL,
  CONSTRAINT PK_UTE_RUOLI PRIMARY KEY (ID_RUOLO));

CREATE TABLE UTE_RUOLI_RISORSE (
  ID_RUOLO            VARCHAR2(50)    NOT NULL,
  ID_RISORSA          VARCHAR2(255)   NOT NULL,
  VAL_RISORSA         VARCHAR2(255),
  CONSTRAINT PK_UTE_RUOLI_RISORSE PRIMARY KEY (ID_RUOLO,ID_RISORSA),
  CONSTRAINT FK_UTE_RUR_RUO FOREIGN KEY (ID_RUOLO) REFERENCES UTE_RUOLI(ID_RUOLO));

CREATE TABLE UTE_UTENTI (
  ID_UTENTE           VARCHAR2(100)   NOT NULL,
  ID_RUOLO            VARCHAR2(50)    NOT NULL,
  CREDENZIALI         VARCHAR2(100)   NOT NULL,
  EMAIL               VARCHAR2(100)   NOT NULL,
  TELEFONO            VARCHAR2(20),
  DT_PRIMO_ACCESSO    TIMESTAMP,
  DT_ULTIMO_ACCESSO   TIMESTAMP,
  DT_ACCESSO          TIMESTAMP,
  COD_ATTIVAZIONE     VARCHAR2(36),
  COD_RICORDAMI       VARCHAR2(36),
  VERIFICATO          NUMBER(10)      NOT NULL,
  ATTIVO              NUMBER(10)      NOT NULL,
  CONSTRAINT PK_UTE_UTENTI PRIMARY KEY (ID_UTENTE),
  CONSTRAINT FK_UTE_UTE_RUO FOREIGN KEY (ID_RUOLO) REFERENCES UTE_RUOLI(ID_RUOLO));

CREATE TABLE UTE_ACCESSI (
  ID_ACCESSO          VARCHAR2(36)    NOT NULL,
  ID_UTENTE           VARCHAR2(100)   NOT NULL,
  DT_LOGIN            TIMESTAMP       NOT NULL,
  DT_LOGOUT           TIMESTAMP,
  CONSTRAINT PK_UTE_ACCESSI PRIMARY KEY (ID_ACCESSO),
  CONSTRAINT FK_UTE_ACC_UTE FOREIGN KEY (ID_UTENTE) REFERENCES UTE_UTENTI(ID_UTENTE));

--
-- Indexes
--

CREATE INDEX IDX_UTE_UTE_EML ON UTE_UTENTI(EMAIL);
CREATE INDEX IDX_UTE_UTE_CAT ON UTE_UTENTI(COD_ATTIVAZIONE);
CREATE INDEX IDX_UTE_UTE_CRI ON UTE_UTENTI(COD_RICORDAMI);
