--
-- Drop tables
--

DROP TABLE IF EXISTS `TAB_SEQUENCES`;

DROP TABLE IF EXISTS `UTE_ACCESSI`;
DROP TABLE IF EXISTS `UTE_UTENTI`;
DROP TABLE IF EXISTS `UTE_RUOLI_RISORSE`;
DROP TABLE IF EXISTS `UTE_RUOLI`;

DROP TABLE IF EXISTS `ANA_COMUNI`;
DROP TABLE IF EXISTS `ANA_REGIONI`;

-- mysql --user=root --password[=password] webapp
-- source C:/prj/dew/webapp-bs-it/mysql/02_drop.sql;
--