--
-- Tables
--

-- Applicazione

CREATE TABLE IF NOT EXISTS ANA_REGIONI (
  ID_REGIONE          VARCHAR(3)     NOT NULL,
  DESCRIZIONE         VARCHAR(50),
  CONSTRAINT PK_ANA_REGIONI PRIMARY KEY (ID_REGIONE));

CREATE TABLE IF NOT EXISTS ANA_COMUNI (
  ID_COMUNE           VARCHAR(6)     NOT NULL,
  FISCALE             VARCHAR(4),
  PROVINCIA           VARCHAR(3),
  DESCRIZIONE         VARCHAR(50),
  ID_REGIONE          VARCHAR(3)     NOT NULL,
  CONSTRAINT PK_ANA_COMUNI PRIMARY KEY (ID_COMUNE),
  CONSTRAINT FK_ANA_COM_REG FOREIGN KEY (ID_REGIONE) REFERENCES ANA_REGIONI(ID_REGIONE));

-- Utenti

CREATE TABLE IF NOT EXISTS UTE_RUOLI (
  ID_RUOLO            VARCHAR(50)          NOT NULL,
  DESCRIZIONE         VARCHAR(100)         NOT NULL,
  ATTIVO              INT                  NOT NULL,
  CONSTRAINT PK_UTE_RUOLI PRIMARY KEY (ID_RUOLO));

CREATE TABLE IF NOT EXISTS UTE_RUOLI_RISORSE (
  ID_RUOLO            VARCHAR(50)          NOT NULL,
  ID_RISORSA          VARCHAR(255)         NOT NULL,
  VAL_RISORSA         VARCHAR(255),
  CONSTRAINT PK_UTE_RUOLI_RISORSE PRIMARY KEY (ID_RUOLO,ID_RISORSA),
  CONSTRAINT FK_UTE_RUR_RUO FOREIGN KEY (ID_RUOLO) REFERENCES UTE_RUOLI(ID_RUOLO));

CREATE TABLE IF NOT EXISTS UTE_UTENTI (
  ID_UTENTE           VARCHAR(100)   NOT NULL,
  ID_RUOLO            VARCHAR(50)    NOT NULL,
  CREDENZIALI         VARCHAR(100)   NOT NULL,
  EMAIL               VARCHAR(100)   NOT NULL,
  TELEFONO            VARCHAR(20),
  DT_PRIMO_ACCESSO    TIMESTAMP NULL DEFAULT NULL,
  DT_ULTIMO_ACCESSO   TIMESTAMP NULL DEFAULT NULL,
  DT_ACCESSO          TIMESTAMP NULL DEFAULT NULL,
  COD_ATTIVAZIONE     VARCHAR(36),
  COD_RICORDAMI       VARCHAR(36),
  VERIFICATO          INT            NOT NULL,
  ATTIVO              INT            NOT NULL,
  CONSTRAINT PK_UTE_UTENTI PRIMARY KEY (ID_UTENTE),
  CONSTRAINT FK_UTE_UTE_RUO FOREIGN KEY (ID_RUOLO) REFERENCES UTE_RUOLI(ID_RUOLO));

CREATE TABLE IF NOT EXISTS UTE_UTENTI_ANAGRAFICHE (
  ID_UTENTE           VARCHAR(100)   NOT NULL,
  ID_ANAGRAFICA       INT            NOT NULL,
  CONSTRAINT PK_UTE_UTENTI_ANAGRAFICHE PRIMARY KEY (ID_UTENTE, ID_ANAGRAFICA) );

CREATE TABLE IF NOT EXISTS UTE_ACCESSI (
  ID_ACCESSO          VARCHAR(36)    NOT NULL,
  ID_UTENTE           VARCHAR(100)   NOT NULL,
  DT_LOGIN            TIMESTAMP      NOT NULL,
  DT_LOGOUT           TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT PK_UTE_ACCESSI PRIMARY KEY (ID_ACCESSO),
  CONSTRAINT FK_UTE_ACC_UTE FOREIGN KEY (ID_UTENTE) REFERENCES UTE_UTENTI(ID_UTENTE));

--
-- Sequences
--

CREATE TABLE TAB_SEQUENCES (
  SEQ_NAME            VARCHAR(50)    NOT NULL,
  SEQ_VAL             INT            NOT NULL,
  CONSTRAINT PK_TAB_SEQUENCES PRIMARY KEY (SEQ_NAME) );

--
-- Indexes
--

CREATE INDEX IDX_UTE_UTE_EML ON UTE_UTENTI(EMAIL);
CREATE INDEX IDX_UTE_UTE_CAT ON UTE_UTENTI(COD_ATTIVAZIONE);
CREATE INDEX IDX_UTE_UTE_CRI ON UTE_UTENTI(COD_RICORDAMI);
