INSERT INTO UTE_RUOLI(ID_RUOLO,DESCRIZIONE,ATTIVO) VALUES('admin', 'Amministratore',  1);
INSERT INTO UTE_RUOLI(ID_RUOLO,DESCRIZIONE,ATTIVO) VALUES('user',  'Utente generico', 1);

COMMIT;

INSERT INTO UTE_UTENTI(ID_UTENTE,ID_RUOLO,CREDENZIALI,EMAIL,DT_PRIMO_ACCESSO,DT_ULTIMO_ACCESSO,DT_ACCESSO,VERIFICATO,ATTIVO) VALUES('admin', 'admin', '92668751', 'admin@dew.org', null, null, null, 1, 1);

COMMIT;